codecov: 
 token: 1c2d278c-599d-4e69-acad-30e53e8280a0
 require_ci_to_pass: yes

ignore:
  - "jambl/src/main/java/jambl/Controller"
  - "jambl/src/main/java/jambl/View"
  - "jambl/src/main/java/jambl/GUIMain.java"
  - "jambl/src/main/java/jambl/Main.java"

coverage:
  target: 97%
  threshold: 0%
